version: '3'

services:
  app:
    container_name: app
    build: .
    tty: true
    command: yarn run-p dev prisma:studio
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - .:/app
    depends_on:
      - mysql
    env_file:
      - .env
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306